<?php


namespace AppBundle\Entity;


use Doctrine\ORM\EntityRepository;

class GenusRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AppBundle:Genus p ORDER BY p.genusname ASC')
            ->getResult();
    }

    public function findOneBy(array $criteria, array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy); // TODO: Change the autogenerated stub
    }
}